name = "braincoin-game-bot" # Убедитесь, что это имя совпадает с именем вашего Worker
   
main = "worker.js" # Путь к вашему файлу точки входа

compatibility_date = "2024-12-26" # Установите текущую или прошедшую дату

[env]
account_id = "your-cloudflare-account-id"
workers_dev = true
route = ""
zone_id = ""

[vars]
TELEGRAM_TOKEN = "AAH3eXTADJAGyeBZCpUE2Ek9NpBCfq0dFAs"




